[package]
name = "macecraft"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
env_logger = "0.11.8"
glam = "0.30.9"
image = "0.25.9"
log = "0.4.29"
pollster = "0.4.0"
wgpu = "27.0.1"
winit = "0.30.12"

